[build]
  command = "pnpm install && pnpm build && cp client/public/_redirects dist/public/_redirects"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.13.0"
  NPM_FLAGS = "--version" # Disable npm
  PNPM_VERSION = "10.4.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["postgres", "drizzle-orm"]

